config/routes.rb
Rails.application.routes.draw do
  resources :home, only: [:index]

  devise_for :users
  resources :subscriptions
  resources :bundles, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root to: 'home#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bundle.rb
class Bundle < ApplicationRecord
  has_many :bundle_subscriptions
  has_many :subscriptions, through: :bundle_subscriptions
  belongs_to :user

  def prebundled_cost_in_cents
    subscriptions.pluck(:cost_in_cents).sum
  end
end

app/models/bundle_subscription.rb
class BundleSubscription < ApplicationRecord
  validates_presence_of :subscription_id, :bundle_id
  belongs_to :bundle
  belongs_to :subscription
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :cost_in_cents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :bundle
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    if current_user.bundle
      current_user.bundle
    else
      new_bundle_path
    end
  end
end

app/controllers/bundles_controller.rb
  class BundlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bundle, only: [:show, :edit, :update, :destroy]

  # GET /bundles
  # GET /bundles.json
  def index
    @bundles = current_user.bundle
  end

  # GET /bundles/1
  # GET /bundles/1.json
  def show
    @subscriptions = @bundle.subscriptions
    @prebundled_cost = @bundle.prebundled_cost_in_cents/100.0
  end

  # GET /bundles/new
  def new
    @subscriptions = Subscription.all
    @bundle = Bundle.new
  end

  # GET /bundles/1/edit
  def edit
    @subscriptions = Subscription.all
    @bundled_subscriptions = @bundle.subscriptions
    @prebundled_cost = @bundle.prebundled_cost_in_cents/100.0
  end

  # POST /bundles
  # POST /bundles.json
  def create
    @bundle = Bundle.create user: current_user
    bundle_subscriptions = create_bundle_subs

    if BundleSubscription.import(bundle_subscriptions)
      redirect_to @bundle, notice: 'Bundle was successfully created.'
    else
      @bundle.destroy
      render :new
    end
  end

  # PATCH/PUT /bundles/1
  # PATCH/PUT /bundles/1.json
  def update
    bundle_subscriptions = create_bundle_subs
    if BundleSubscription.import(bundle_subscriptions)
      @bundle.bundle_subscriptions.where.not(id: bundle_subscriptions).destroy_all
      redirect_to @bundle, notice: 'Bundle was successfully updated.'
    else
      edit
      flash[:alert] = 'Something went wrong while updating your bundle. Please try again.'
      render :edit and return
    end
  end

  # DELETE /bundles/1
  # DELETE /bundles/1.json
  def destroy
    @bundle.destroy
    respond_to do |format|
      format.html { redirect_to bundles_url, notice: 'Bundle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def create_bundle_subs
      bundle_subscriptions = []
      bundle_params[:bundle_subscriptions].each do |subscription_id|
        bundle_subscriptions << BundleSubscription.new(bundle_id: @bundle.id, subscription_id: subscription_id)
      end
      bundle_subscriptions
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_bundle
      @bundle = Bundle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bundle_params
      params.require(:bundle).permit(bundle_subscriptions: [])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.bundle
      redirect_to current_user.bundle
    else
      redirect_to new_bundle_path
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  def index
    @subscriptions = Subscription.all
  end

  def show
  end

  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.create subscription_params
    redirect_to subscriptions_path
  end

  def edit
  end

  def update
    @subscription.update subscription_params
    redirect_to @subscription
  end

  def destroy
    @subscription.destroy
    redirect_to subscriptions_path
  end


  private
    def set_subscription
      @subscription = Subscription.find params[:id]
    end

    def subscription_params
      params.require(:subscription).permit(:name, :cost_in_cents)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.email.downcase!
    if @user.save
      flash[:notice] = 'Account successfully created!'
      redirect_to root_path
    else
      flash.now.alert = 'Oops. Check your email and password and try again.'
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bundles_helper.rb
module BundlesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bundles/_form.html.haml
= form_for @bundle do |f|
  - if @bundle.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bundle.errors.count, "error")} prohibited this bundle from being saved:"
      %ul
        - @bundle.errors.full_messages.each do |message|
          %li= message

  .row.mt-4
    .col-md-8
      %h4
        Available Subscriptions
      %p
        Add two or more subscriptions to create a bundle
    .col-md-4
      .d-flex.flex-row.justify-content-center.align-items-end
        %div
          %dt Pre-bundled Total
          %dd#unbundled-cost= number_to_currency @prebundled_cost || 0
        .ml-3
          %dt Bundled Total
          %dd#bundled-cost Not yet available
  .row.mt-3
    .col-md-12
      %table.table.table-striped
        %tr
          %th{scope: 'col', style: 'width: 33%'} Name
          %th{scope: 'col', style: 'width: 33%'} Pre-bundled Cost
          %th{scope: 'col', style: 'width: 33%'} Bundle
        - @subscriptions.each do |subscription|
          %tr.subscription-row
            = hidden_field :cost_in_cents, subscription.cost_in_cents, value: subscription.cost_in_cents, class: 'cost-in-cents'

            %td= subscription.name
            %td= number_to_currency subscription.cost_in_cents/100.0
            %td
              .btn-group-toggle{'data-toggle': 'buttons'}
                = f.label :bundle_subscriptions, class: 'btn add-subscription ' + (@bundled_subscriptions.try(:include?, subscription) ? 'active btn-success selected' : 'btn-secondary') do
                  = f.check_box :bundle_subscriptions, {multiple: true, checked: @bundled_subscriptions.try(:include?, subscription)}, subscription.id, false
                  .checkbox-text= @bundled_subscriptions.try(:include?, subscription) ? 'Added' : 'Add'


      .form-group
        = f.submit 'Save', class: 'btn btn-primary'

app/views/bundles/edit.html.haml
%h2.mt-4 Editing bundle

= render 'form'

= link_to 'Show your bundle', @bundle

app/views/bundles/index.html.haml
%h1 Listing bundles

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @bundles.each do |bundle|
      %tr
        %td= link_to 'Show', bundle
        %td= link_to 'Edit', edit_bundle_path(bundle)
        %td= link_to 'Destroy', bundle, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Bundle', new_bundle_path

app/views/bundles/new.html.haml
%h1.mt-3 Create your bundle

= render 'form'

app/views/bundles/show.html.haml
.row.mt-4
  .col-md-12
    %h2 Showing your bundle
    = link_to 'Edit your bundle', edit_bundle_path(@bundle), class: 'btn btn-secondary'
    .mt-3.d-flex.flex-row.justify-content-start.align-items-center
      .mr-3
        %dt Pre-bundled Cost
        %dd= number_to_currency(@prebundled_cost)

      %div
        %dt Bundled Cost
        %dd Not yet available

    = render 'subscriptions/subscription_list'

    -# TODO: Repurpose create and edit form
    -# = link_to 'Edit', edit_bundle_path(@bundle)

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to 'BundleBuddi', new_bundle_path, class: 'navbar-brand'
  %button.navbar-toggler{type: 'button', 'data-toggle': 'collapse', 'data-target': '#navbarSupportedContent', 'aria-controls': 'navbarSupportedContent', 'aria-expanded': false, 'aria-label': 'Toggle navigation' }
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      - if current_user
        - if current_user.bundle
          %li.nav-item
            = link_to current_user.bundle, class: 'nav-link', disabled: !current_user.bundle do
              My Bundle
        - else
          %li.nav-item
            = link_to new_bundle_path, class: 'nav-link' do
              Create Bundle
              - if current_page?(controller: 'bundles', action: 'new')
                %span.sr-only (current)
        - if current_user.admin?
          %li.nav-item
            = link_to subscriptions_path, class: 'nav-link' do
              Edit Subscriptions (Admin Only)
              - if current_page?(controller: 'subscriptions')
                %span.sr-only (current)
    %ul.navbar-nav
      - if current_user
        %li.nav-item
          = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link'
      - else
        %li.nav-item
          = link_to 'Log in', new_user_session_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Sign up', new_user_registration_path, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1'}
    %title Bundlebuddi
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      - if notice
        .mt-3.alert.alert-primary= notice
      - if alert
        .mt-3.alert.alert-danger= alert
      = yield

app/views/subscriptions/_form.html.haml
= form_for @subscription do |f|
  - if @subscription.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subscription.errors.count, "error")} prohibited this subscription from being saved:"
      %ul
        - @subscription.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-6
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :cost_in_cents
        = f.number_field :cost_in_cents, class: 'form-control'
      .actions
        = f.submit 'Save', class: 'btn btn-primary'

app/views/subscriptions/_subscription_list.html.haml
%table.table.table-striped
  %tr
    %th Name
    %th Pre-bundling Cost
    - if current_page?(controller: :subscriptions)
      %th Edit
      %th Delete
  - @subscriptions.each do |subscription|
    %tr
      %td= subscription.name
      %td= number_to_currency subscription.cost_in_cents/100.0
      - if current_page?(controller: :subscriptions)
        %td= link_to 'Edit', edit_subscription_path(subscription)
        %td= link_to 'Delete', { action: :destroy, id: subscription.id }, method: :delete, data: { confirm: 'Are you sure?' }

app/views/subscriptions/edit.html.haml
%h1 Editing subscription

= render 'form'

= link_to 'Show', @subscription
\|
= link_to 'Back', subscriptions_path

app/views/subscriptions/index.html.haml
%h1
  Available Subscriptions
= render 'subscription_list'

= link_to 'New Subscription', new_subscription_path

app/views/subscriptions/new.html.haml
%h1 New subscription

= render 'form'

= link_to 'Back', subscriptions_path

app/views/subscriptions/show.html.haml
%p#notice= notice

%dt Name
%dd= @subscription.name

%dt Cost
%dd= "$#{@subscription.cost_in_cents/100.0}"

= link_to 'Edit', edit_subscription_path(@subscription)
\|
= link_to 'Back', subscriptions_path

app/views/users/new.html.haml
.row.mt-4
  .col-md-6.offset-md-3
    %h1 Sign Up

    = form_for @user do |f|

      .form-group.mt-3
        = f.label :email
        = f.text_field :email, class: 'form-control'

      .form-group
        = f.label :password
        = f.password_field :password, class: 'form-control'

      .form-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: 'form-control'

      .form-group
        = f.submit 'Sign up!', class: 'btn btn-primary'